### ISSUE TITLE
pandoc should use: --from markdown-yaml_metadata_block

### ISSUE THREAD

**Issue by dlmiles** [TinyTapeout/tt-support-tools#78]
This is in related to the https://discord.com/channels/1009193568256135208/1302455447269281823 thread on well formed markdown format docs not completing the `docs` GHA task.

The use of `\_` appears to be related to the TeX format requirement not a MD format requirement.   Pandoc should have converted/escaped the MD document for TeX format if that is what it needs to process it.  An internal bug there somewhere.

MD allows use of horizontal rules https://www.markdownguide.org/basic-syntax/#horizontal-rules in the form `---` and this appears to be triggering the YAML parser used to parse the top block.

Top of document looks like:

```yaml
---
documentclass: scrartcl
geometry: "left=2cm,right=2cm,top=2cm,bottom=3cm"
fontsize: 14pt
mainfont: Latin Modern Sans
header-includes:
- \usepackage{hyperref}
- \hypersetup{colorlinks=false,
          allbordercolors={0 0 0},
          pdfborderstyle={/S/U/W 1}}
---

# MULDIV unit (8-bit signed/unsigned)

```

I tried replacing the 2nd `---` with `...` to indicate eod-of-document to YML but it did not make a difference.

Using the option `--from markdown-yaml_metadata_block` does allow it to be processed without error.
I guess this defeats a format auto-detection mechanism which maybe causing the issue the problem.  `pandoc` is not exactly sure the following data (after YAMl headers) is MD format.
